config/routes.rb
Rails.application.routes.draw do
  

  	root                                'sessions#new'
  	post 'login' 		                =>  'sessions#check'
	  delete 'logout'                 =>  'sessions#destroy'

  	get 'users'                     =>  'users#index'
    get 'users/show/:id'            =>  'users#show'
    get 'signup'                    =>  'users#new'
    post 'signup'                   =>  'users#create'  
    get 'users/edit/:id'            =>  'users#edit'
    post 'users/edit/:id'           =>  'users#update'   
    delete 'users/destroy/:id'      =>  'users#destroy'

    get 'guide'                     =>  'static#guide'
    get 'listes'                    =>  'static#listes'
    post 'listes'                   =>  'static#listes_choix'
    post 'intervenant'              =>  'static#interv_create'
    delete 'intervenant/:id'        =>  'static#interv_destroy'
    post 'ville'                    =>  'static#ville_create'
    delete 'ville/:id'              =>  'static#ville_destroy'
    post 'type_renc'                =>  'static#type_renc_create'
    delete 'type_renc/:id'          =>  'static#type_renc_destroy'

    get 'usagers'                   =>  'usagers#index'
    get 'pqi'		              	    =>  'usagers#pqi'
    get 'pqi/:ville'          	    =>  'usagers#pqi'
	  get 'usagers/new'               =>  'usagers#new'
  	post 'usagers/new'              =>  'usagers#create'
  	get 'usagers/edit_comp/:id'     =>  'usagers#edit_comp'
  	post 'usagers/edit_comp/:id'    =>  'usagers#post_comp'
  	get 'usagers/edit/:id'          =>  'usagers#edit'
  	get 'usagers/fiche/:id'         =>  'usagers#fiche'
    get 'usagers/fiche_jour/:id'    =>  'usagers#fiche_jour'
    post 'usagers/edit/:id'         =>  'usagers#update'
    get 'usagers/:id'               =>  'usagers#show'
    delete 'usagers/:id'            =>  'usagers#destroy'

   
  	get 'groupes'                   =>  'groupes#index'
  	get 'groupes/show/:id'          =>  'groupes#show'
  	get 'groupes/edit/:id'          =>  'groupes#edit'
  	post 'groupes/edit/:id'         =>  'groupes#update'
  	delete 'groupes/edit/:id'       =>  'groupes#destroy'


    get 'maraudes'                  =>  'maraudes#index'
    get 'maraudes/show/:id'         =>  'maraudes#show'
  	get 'maraudes/new'              =>  'maraudes#new'
  	post 'maraudes/new'             =>  'maraudes#create'
  	get 'maraudes/edit/:id'         =>  'maraudes#edit'
  	post 'maraudes/edit/:id'        =>  'maraudes#update'
  	delete 'maraudes/edit/:id'      =>  'maraudes#destroy'

    get 'structures'                =>  'structures#index'
    get 'structures/show/:id'       =>  'structures#show'
    get 'structures/new'            =>  'structures#new'
    post 'structures/new'           =>  'structures#create'
    get 'structures/edit/:id'       =>  'structures#edit'
    post 'structures/edit/:id'      =>  'structures#update'
    delete 'structures/edit/:id'    =>  'structures#destroy'


  	get 'rencontres/new/:id'        =>  'rencontres#new'
    post 'rencontres/new/:id'       =>  'rencontres#create'
	  get 'rencontres/edit_form/:id'  =>  'rencontres#edit_form'
    post 'rencontres/edit_form/:id' =>  'rencontres#post_form'
    get 'rencontres/edit/:id'       =>  'rencontres#edit'
    post 'rencontres/edit/:id'      =>  'rencontres#update'
    get 'rencontres/groupe/:id'     =>  'rencontres#new_groupe'
    post 'rencontres/groupe/:id'    =>  'rencontres#post_groupe'

    get 'stats'                     =>  'stats#show'
    post 'stats'                    =>  'stats#create'
    get 'stats/:ville/:categorie'   => 'stats#index'



end

app/models/usager.rb
class Usager < ActiveRecord::Base
  has_many :rencontres, :dependent => :destroy
  has_many :enfants, :dependent => :destroy
  belongs_to :groupe, optional: true
  has_and_belongs_to_many :structures

  accepts_nested_attributes_for :enfants, reject_if: lambda { |a| a[:nom].blank? && a[:prenom].blank? },
                                          allow_destroy: true

  default_scope -> { }

  validates :sexe, presence: true
  validates :ville, presence: true
  validate :at_least_one
  validate :at_least_one2

  def groupe_nom
    groupe.try(:nom)
  end

  def groupe_nom=(nom)
    self.groupe = Groupe.find_or_create_by(nom: nom.split(' ').map(&:capitalize).join(' ').split('-').map(&:capitalize).join('-')) if nom.present?
  end


  def self.search(search)
    if search
      where("usagers.nom ILIKE ? OR usagers.ville ILIKE? OR usagers.prenom ILIKE? OR usagers.adresse ILIKE? OR usagers.adresse_précis ILIKE? OR usagers.sexe ILIKE? OR to_char(usagers.date_naissance, 'DD/MM/YYYY') ILIKE? OR usagers.tel ILIKE? OR usagers.nom2 ILIKE? OR usagers.prenom2 ILIKE? OR usagers.sexe2 ILIKE? OR usagers.tel2 ILIKE? OR to_char(usagers.date_naissance2, 'DD/MM/YYYY') ILIKE? ", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    end
  end

  private
    def at_least_one
      if self.prenom.blank? && self.nom.blank?
        self.errors.add(:base, "Please fill at least the name or surname")
      end
    end

    def at_least_one2
      if self.couple == true      
        if (self.prenom2.blank? && self.nom2.blank?) || sexe2.blank?
          self.errors.add(:base, "Please fill at least the name or surname")
        end
      end      
    end

end

app/controllers/usagers_controller.rb
class UsagersController < ApplicationController

	  before_action :logged_in_user,  only: [:index, :pqi, :new, :create, :edit_comp, :post_comp, :edit, :fiche, :fiche_jour, :update, :show, :destroy]
    before_action :benev_user,      only: [:edit_comp, :post_comp, :edit, :fiche, :fiche_jour, :update]
    before_action :correct_user,    only: [:destroy]

  	def index
  		if params[:search]
      	@usagers = Usager.search(params[:search]).paginate(page: params[:page], per_page: 50)
      	if @usagers.empty?
        	@usagers = Usager.search(params[:search].split('/').reverse.join('-')).paginate(page: params[:page], per_page: 50)
      	end
    	else
     		@usagers = Usager.paginate(page: params[:page], per_page: 50)
    	end
   
    	if params[:ordre_de_tri] == "Ordre chronologique de modification" 
		    @usagers = @usagers.order('updated_at DESC')
		    @proposition=["Ordre chronologique de modification", "Ordre alphabétique"]		    
		  else
		    @usagers= @usagers.order('nom ASC').order('prenom ASC') 
		    @proposition=["Ordre alphabétique", "Ordre chronologique de modification"]
		  end
    end

    def pqi
      @villes = []
      Ville.where(ville_93: true).order('nom ASC').each do |v|
        @villes << "#{v.nom}"
      end

      if params[:ordre_de_tri] == "Ordre géographique"
        @usagers = Usager.where(pqi: true, ville: params[:ville]).order('adresse ASC, adresse_précis ASC, nom ASC') unless not params[:ville]
        @proposition = ["Ordre géographique", "Ordre alphabétique"]
      else
        @usagers = Usager.where(pqi: true, ville: params[:ville]).order('nom ASC, prenom ASC') unless not params[:ville]
        @proposition = ["Ordre alphabétique", "Ordre géographique"]
      end

      @ville_actuelle = params[:ville]
    end


    def new
      @villes = []
      Ville.order("ville_93 DESC").order('nom ASC').each do |v|
        @villes << ["#{v.nom}"]
      end
    end

    def create

      @usager = Usager.new(usager_params)

      @usager.user_id = @current_user.id

      if @usager.nom
        @usager.nom.upcase!
      end
      if @usager.nom2
        @usager.nom2.upcase!
      end
      @usager.enfants.each do |enf|
        if enf.nom
          enf.nom.upcase!
        end
      end

      if @usager.enceinte
        if @usager.sexe == "Mr"
          @usager.enceinte = false
        end
      end

      if @usager.enceinte2
        if @usager.sexe2 == "Mr"
          @usager.enceinte2 = false
        end
      end

      if @usager.save
        if @usager.ref.present?
          interv = Intervenant.find_or_create_by(nom: @usager.ref.split(' ').map(&:capitalize).join(' ').split('-').map(&:capitalize).join('-'))
          interv.ref = true
          interv.save
        end
        if @usager.pqi
          @usager.pqi_histo = ""
          @usager.pqi_histo << Date.today.strftime("%d/%m/%y")
          @usager.save
        end
        if @usager.dmde && (@usager.date_dmde==nil)
          @usager.update(date_dmde: @usager.created_at)
        end

        flash[:success] = "Nouvel usager ajouté !"
        if @current_user.benev?
          redirect_to "/usagers/#{@usager.id}"
        else
          redirect_to "/usagers/edit_comp/#{@usager.id}"
        end

      else
        flash[:danger] = "Ajoutez au moins le prénom ou le nom de chaque usager ainsi que leur sexe et la ville !"
        redirect_to '/usagers/new'
      end
    end

    def edit_comp
      @usager = Usager.find(params[:id])
      @ressources = [ ["Salaire", "Salaire"],
                    ["Retraite", "Retraite"],
                    ["RSA", "RSA"],
                    ["AAH", "AAH"],
                    ["Prestation(s) familiale(s)", "Prestation(s) familiale(s)"],
                    ["ATA", "ATA"],
                    ["ASS", "ASS"],
                    ["ARE", "ARE"],
                    ["Rémunération de formation", "Rémunération de formation"],
                    ["Pension d'invalidité", "Pension d'invalidité"],
                    ["Autre", "Autre"],
                    ["Sans ressources", "Sans ressources"]]
      @prestas_med = [["CMU", "CMU"],
                      ["CMUC", "CMUC"],
                      ["AME", "AME"],
                      ["Régime général", "Régime général"]]
    end


    def post_comp
      @usager = Usager.find(params[:id])
      params[:usager][:ressources] = params[:usager][:ressources].reject{ |a| a == '0' }.join("\n")
      params[:usager][:prestas_med] = params[:usager][:prestas_med].reject{ |a| a == '0' }.join("\n")
      
      if @usager.update(comp_params)
        flash[:success] = "Informations complémentaires éditées"
        if Usager.maximum("id") == @usager.id
          redirect_to "/rencontres/new/#{@usager.id}"
        else
          redirect_to "/usagers/#{@usager.id}"
        end
      else
        flash[:danger] = "Problème inconnu, veuillez réessayer"
        redirect_to "/usagers/edit_comp/#{@usager.id}"
      end     
    end

    def edit
      session[:stored] = "edit"

      @villes = [["Ville inconnue"], ["Autre (hors 93)"]]
      Ville.where(ville_93: true).order('nom ASC').each do |v|
        @villes << ["#{v.nom}"]
      end

      @usager = Usager.find(params[:id])
    end

    def fiche
      @usager = Usager.find(params[:id])
      session[:stored] = "fiche"
    end

    def fiche_jour
      @usager = Usager.find(params[:id])
      session[:stored] = "fiche_jour"
    end

    def update
      @usager = Usager.find(params[:id])
      statut = session[:stored]
      session.delete(:stored)

      if statut == "edit"

        stored_pqi = @usager.pqi

        if @usager.update(usager_params)
          if @usager.ref.present?
            interv = Intervenant.find_or_create_by(nom: @usager.ref.split(' ').map(&:capitalize).join(' ').split('-').map(&:capitalize).join('-'))
            interv.ref = true
            interv.save
          end

          if @usager.dmde && (@usager.date_dmde==nil)
            @usager.update(date_dmde: @usager.updated_at)
          end

          if @usager.pqi != stored_pqi
            if @usager.pqi
              if @usager.pqi_histo
                @usager.pqi_histo << " ///// "
              else
                @usager.pqi_histo = ""
              end
            else
              @usager.pqi_histo << " - " unless @usager.pqi_histo.nil?
            end
            arr = @usager.pqi_histo.split(' ///// ')
            if arr.last == "#{Date.today.strftime("%d/%m/%y")} - "
              if arr.length >= 2
                @usager.pqi_histo = arr[0..(arr.length-2)].join(' ///// ')
              else
                @usager.pqi_histo = nil
              end
            else
              @usager.pqi_histo << Date.today.strftime("%d/%m/%y") unless @usager.pqi_histo.nil?
            end
          end

          if @usager.nom
            @usager.nom.upcase!
          end
          if @usager.nom2
            @usager.nom2.upcase!
          end
          @usager.enfants.each do |enf|
            if enf.nom
              enf.nom.upcase!
            end
          end

          if @usager.enceinte
            if @usager.sexe == "Mr"
              @usager.enceinte = false
            end
          end

          if @usager.enceinte2
            if @usager.sexe2 == "Mr"
              @usager.enceinte2 = false
            end
          end

          if params[:usager][:groupe_nom] == ""
            @usager.update(groupe_id: nil)
          end

          @usager.save

          flash[:success] = "Usager édité"
          redirect_to "/usagers/#{@usager.id}"

        else 
          flash[:danger] = "Mise à jour impossible. Veillez à remplir les informations nécessaires (Nom et/ou prénom, ville et sexe)."
          redirect_to "/usagers/edit/#{@usager.id}"
        end

      elsif statut == "fiche"

        @usager.update(fiche: params[:usager][:fiche])
        flash[:success] = "Fiche de rencontres usager éditée"
        redirect_to "/usagers/#{@usager.id}"

      elsif statut == "fiche_jour"

        @usager.update(fiche_jour: params[:usager][:fiche_jour])
        flash[:success] = "Fiche de suivi jour usager éditée"
        redirect_to "/usagers/#{@usager.id}"

      end
    end

    def show
      @usager = Usager.find(params[:id])
    end

    def destroy
      Usager.find(params[:id]).destroy
      flash[:success] = "Usager supprimé"
      redirect_to usagers_path
    end

    private

    def correct_user
      @usager = Usager.find(params[:id])
      redirect_back(fallback_location: root_path) unless  ("#{@current_user.id}" == @usager.user_id || @current_user.admin?)
    end
      
    def usager_params
      params.require(:usager).permit( :nom,
                                      :prenom,
                                      :sexe,
                                      :enceinte,
                                      :ville,
                                      :adresse,
                                      :adresse_précis,
                                      :date_naissance,
                                      :tel,
                                      :notes,
                                      :pqi,
                                      :pqi_histo,
                                      :fiche,
                                      :groupe_nom,
                                      :ressources,
                                      :montant,
                                      :ref,
                                      :dmde,
                                      :date_dmde,
                                      :vu,
                                      :couple,
                                      :nom2,
                                      :prenom2,
                                      :sexe2,
                                      :date_naissance2,
                                      :tel2,
                                      :enceinte2,
                                      enfants_attributes: [ :id,

app/helpers/usagers_helper.rb
module UsagersHelper
	def dates_5(dat)
    if dat
      if dat.length > 52
        d = dat.split(' - ')
        d[0..4].join(' - ') 
      else
        dat
      end
    end
  end
end

app/views/usagers/_edit_comp_form.html.erb
<%= simple_form_for(:usager, url: "/usagers/edit_comp/#{@usager.id}", method: :post) do |f| %>

	<div id="tabs">
    <ul>
      <li><a href="#tab-1">Ressources</a></li>
      <li><a href="#tab-2">Suivi social</a></li>
      <li><a href="#tab-3">Suivi médical</a></li>
      <li><a href="#tab-4">Autres informations</a></li>
    </ul>
    <div id="tab-1">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6">
          <% for ress in @ressources[0..5] do %>
          	<% if @usager.ressources.present? && @usager.ressources.split("\n").include?("#{ress.first}") %>
    			    <%= f.check_box :ressources, { :multiple => true, :checked => true }, "#{ress.first}" %>
    			   	<%= ress.first %><br>
    			  <% else %>
    			    <%= f.check_box :ressources, { :multiple => true, :checked => false }, "#{ress.first}" %>
    			    <%= ress.first %><br>
    			  <% end %>
    		  <% end %>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6">
          <% for ress in @ressources[6..11] do %>
            <% if @usager.ressources.present? && @usager.ressources.split("\n").include?("#{ress.first}") %>
              <%= f.check_box :ressources, { :multiple => true, :checked => true }, "#{ress.first}" %>
              <%= ress.first %><br>
            <% else %>
              <%= f.check_box :ressources, { :multiple => true, :checked => false }, "#{ress.first}" %>
              <%= ress.first %><br>
            <% end %>
          <% end %>
        </div>
      </div>
      <br>
      <div class="text-center">
		    <%= f.label :montant, "Montant (en €)" %>
		    <%= f.number_field :montant, step: '0.01' %>
      </div>
    </div>

    <div id="tab-2">
      <div>
        <div class="form-inline">
          <%= f.check_box :sejour, class: 'form-control check' %><span> Carte de séjour</span>

          <%= f.check_box :cfr, class: 'form-control check' %><span> CNI/Passeport</span>
        </div>

        <div class="appear">
          <%= f.label :carte_date, "Date de validité" %>
          <div class="input-group date" id="datepicker">
            <%= f.text_field :carte_date, class: 'form-control', data: { date_format: 'DD/MM/YYYY', locale: 'fr' } %>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
          </div>
        </div>
      </div>
      <hr style="border-top:1px solid #ddd;">
      <div>
        <div class="form-inline">
          <%= f.check_box :dom, class: 'form-control check' %><span> Domiciliation</span>
        </div>

        <div class="appear">
          <%= f.label :dom_org, "Organisme" %>
          <%= f.text_field :dom_org, class: 'form-control' %><br>

          <%= f.label :dom_adr, "Adresse" %>
          <%= f.text_field :dom_adr, class: 'form-control' %>
        </div>
      </div>
      <hr style="border-top:1px solid #ddd;">
      <div>
        <div class="form-inline">
          <%= f.check_box :tut, class: 'form-control check' %><span> Tutelle</span>

          <%= f.check_box :cur, class: 'form-control check' %><span> Curatelle</span>
        </div>

        <div class="appear">
          <%= f.label :tutcur_org, "Organisme" %>
          <%= f.text_field :tutcur_org, class: 'form-control' %>
        </div>
      </div>
      <hr style="border-top:1px solid #ddd;">
      <div>
        <div class="form-inline">
          <%= f.check_box :suivi, class: 'form-control check' %><span> Service social de suivi</span>
        </div>

        <div class="appear">
          <%= f.label :suivi_org, "Organisme" %>
          <%= f.text_field :suivi_org, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div id="tab-3">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6">
          <h4>Prestations médicales</h4>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6">
          <% for presta in @prestas_med do %>
            <% if @usager.prestas_med.present? && @usager.prestas_med.split("\n").include?("#{presta.first}") %>
              <%= f.check_box :prestas_med, { :multiple => true, :checked => true }, "#{presta.first}" %>
              <%= presta.first %><br>
            <% else %>
              <%= f.check_box :prestas_med, { :multiple => true, :checked => false }, "#{presta.first}" %>
              <%= presta.first %><br>
            <% end %>
          <% end %>
        </div>
      </div>
      <hr style="border-top:1px solid #ddd;">

      <div>
        <div class="form-inline">
          <%= f.check_box :medecin, class: 'form-control check' %><span> Médecin traitant</span>
        </div>

        <div class="appear">
          <%= f.label :medecin_infos, "Nom, coordonnées, informations" %>
          <%= f.text_area :medecin_infos, rows: 2, class: 'form-control' %>
        </div>
      </div>
      <hr style="border-top:1px solid #ddd;">

      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6 form-inline">
          <%= f.check_box :pb_sante, class: 'form-control check' %><span> Problématique de santé</span>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6 form-inline">
          <%= f.check_box :mobil, class: 'form-control check' %><span> Mobilité réduite</span>
        </div>
      </div>
      <hr style="border-top:1px solid #ddd;">

      <h4 class="text-center">Informations complémentaires</h4>
      <%= f.text_area :infos_sante, rows: 5, class: 'form-control' %>
    </div>

    <div id="tab-4">
      <%= f.text_area :autres_infos, rows: 10, class: 'form-control' %>
    </div>
  </div>
	
  <div class="text-center">
    <br><%= f.submit "Enregistrer les modifications", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/usagers/index.html.erb
<h1>
  Usagers
  <br><%= link_to "Index des groupes", groupes_path, class: 'btn btn-info' %>
</h1>



<%= will_paginate @usagers %>

<%= form_tag(usagers_path, :method => "get", id: "search-form", role: 'search', class: "navbar navbar-search") do %>
  <div class="form-group col-md-4 col-sm-4 col-xs-4">
    <%= text_field_tag :search, params[:search], placeholder: "Rechercher des usagers", class: 'form-control' %>

    <%= select_tag :ordre_de_tri, options_for_select(@proposition), class: 'form-control' %>
  </div>

  <%= submit_tag "Rechercher / Modifier l'ordre", class: 'btn btn-default' %>
<% end %>

<h4>Au passage de la souris, en vert les usagers sur PQI, en rouge ceux qui n'y sont pas.</h4>

<h4 class="text-right"><%= pluralize(@usagers.count, "usager") %></h4>

<% if !@usagers.empty? %>
  <table class="usagers table table-responsive table-hover text-center">
    <tr id="table_head">
      <th>Identité</th>
      <th>Adresse</th>
      <th>Dernières rencontres</th>
      <% if @current_user.admin? %>
        <th>Edition et Suppression (privilège admin)</th>
      <% end %>
    </tr>
    <% @usagers.each do |usager| %>

    <tr id="usager" <% if usager.pqi %> class="pqi" <% else %> class="no-pqi" <% end %> >
    	<td>
    		<% if usager.enfants.any? && usager.couple %>
      			<%= link_to "Famille #{usager.sexe} #{usager.nom} #{usager.prenom} et #{usager.sexe2} #{usager.nom2} #{usager.prenom2}", "/usagers/#{usager.id}" %>
    		<% elsif usager.enfants.any? && (not usager.couple) %>
      			<%= link_to "Famille #{usager.sexe} #{usager.nom} #{usager.prenom}", "/usagers/#{usager.id}" %>
    		<% elsif (not usager.enfants.any?) && usager.couple %>
      			<%= link_to "Couple #{usager.sexe} #{usager.nom} #{usager.prenom} et #{usager.sexe2} #{usager.nom2} #{usager.prenom2}", "/usagers/#{usager.id}" %>
    		<% else %>
      			<%= link_to "#{usager.sexe} #{usager.nom} #{usager.prenom}", "/usagers/#{usager.id}" %>
    		<% end %>

    		<% if usager.enfants.any? %>
      			<br><%= pluralize(usager.enfants.count, 'enfant') %>
    		<% end %>

    		<% if usager.couple %>
      			<% if usager.date_naissance? %>
        			<br><%= "1: #{usager.date_naissance.strftime("%d/%m/%Y")}" %>
      			<% end %>

      			<% if usager.date_naissance2? %>
        			<br><%= "2: #{usager.date_naissance2.strftime("%d/%m/%Y")}" %>
      			<% end %>
    		<% else %>
      			<% if usager.date_naissance? %>
        			<br><%= "#{usager.date_naissance.strftime("%d/%m/%Y")}" %>
      			<% end %>
    		<% end %>

    		<% if usager.couple %>
      			<% if usager.tel? && usager.tel != "" %>
        			<br><%= "1: #{usager.tel}" %>
      			<% end %>
      			<% if usager.tel2? && usager.tel2 != "" %>
       				<br><%= "2: #{usager.tel2}" %>
      			<% end %>
    		<% else %>
      			<% if usager.tel? && usager.tel != "" %>
        			<br><%= "#{usager.tel}" %>
      			<% end %>
    		<% end %>

    		<% if usager.ref.present? %>
      			<br><small>Référent : <%= usager.ref %></small>
    		<% end %>
    		<% if usager.groupe && usager.groupe.nom != "Sans groupe" %>
      			<br><%= link_to "#{usager.groupe.nom}", "/groupes/show/#{usager.groupe.id}" %>
    		<% end %> 

		</td>

    	<td>

    	<%= "#{usager.ville.upcase}" %>
    	<% if usager.adresse %>
      		<br><%= "#{usager.adresse}" %>
    	<% end %>
    	<% if usager.adresse_précis %>
      		<br><%= "#{usager.adresse_précis}" %>
    	<% end %>
  		
  		</td>

    	<td> 

    	<% dates_renc = [] %>
    	<% Rencontre.where(usager_id: usager.id, prev: false, dnv: false, tel: false).order('date DESC').each do |r| %>
      		<% dates_renc << "#{r.date.strftime("%d/%m/%y")}" %>
    	<% end %>
    	<%= dates_5(dates_renc.join(' - ')) %><br>

    	<% if Rencontre.find_by(usager_id: usager.id, prev: true) %>
      		<% n = Rencontre.where(usager_id: usager.id, prev: true).count %>
      		<%= pluralize(n, "rencontre") %> <%= "prévue".pluralize(n) %><br>
    	<% end %>

    	<%= link_to "Ajouter une rencontre", "/rencontres/new/#{usager.id}", id: 'ajout-rencontre', "data-no-turbolink" => true %>

    	</td>

    	<% if @current_user.admin? %>
    	
    	<td>

    	<%= link_to "Modifier", "/usagers/edit/#{usager.id}" %><br>
      	<%= link_to "Supprimer", "/usagers/#{usager.id}",  method: :delete,
                                        data: { confirm: "Etes-vous sûr(e) ?" } %>

    	 </td>
    	 
    	<% end %>

    </tr>

   <% end %>


  </table>
<% else %>
  <p class="lead text-center">Aucun usager correspondant au(x) terme(s) : "<%= params[:search] %>".</p>
<% end %>

app/views/usagers/new.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<h1>Nouvel usager</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
    <h4>
      On renseignera au moins le nom ou le prénom de chaque usager, ainsi que sa ville et son sexe. <br><br>
      Date de naissance : utiliser le bouton "calendrier"
    </h4>
  </div>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
    <%= render 'form' %>
  </div>
</div>