config/routes.rb
Rails.application.routes.draw do
  

  	root                                'sessions#new'
  	post 'login' 		                =>  'sessions#check'
	  delete 'logout'                 =>  'sessions#destroy'

  	get 'users'                     =>  'users#index'
    get 'users/show/:id'            =>  'users#show'
    get 'signup'                    =>  'users#new'
    post 'signup'                   =>  'users#create'  
    get 'users/edit/:id'            =>  'users#edit'
    post 'users/edit/:id'           =>  'users#update'   
    delete 'users/destroy/:id'      =>  'users#destroy'

    get 'guide'                     =>  'static#guide'
    get 'listes'                    =>  'static#listes'
    post 'listes'                   =>  'static#listes_choix'
    post 'intervenant'              =>  'static#interv_create'
    delete 'intervenant/:id'        =>  'static#interv_destroy'
    post 'ville'                    =>  'static#ville_create'
    delete 'ville/:id'              =>  'static#ville_destroy'
    post 'type_renc'                =>  'static#type_renc_create'
    delete 'type_renc/:id'          =>  'static#type_renc_destroy'

    get 'usagers'                   =>  'usagers#index'
    get 'pqi'		              	    =>  'usagers#pqi'
    get 'pqi/:ville'          	    =>  'usagers#pqi'
	  get 'usagers/new'               =>  'usagers#new'
  	post 'usagers/new'              =>  'usagers#create'
  	get 'usagers/edit_comp/:id'     =>  'usagers#edit_comp'
  	post 'usagers/edit_comp/:id'    =>  'usagers#post_comp'
  	get 'usagers/edit/:id'          =>  'usagers#edit'
  	get 'usagers/fiche/:id'         =>  'usagers#fiche'
    get 'usagers/fiche_jour/:id'    =>  'usagers#fiche_jour'
    post 'usagers/edit/:id'         =>  'usagers#update'
    get 'usagers/:id'               =>  'usagers#show'
    delete 'usagers/:id'            =>  'usagers#destroy'

   
  	get 'groupes'                   =>  'groupes#index'
  	get 'groupes/show/:id'          =>  'groupes#show'
  	get 'groupes/edit/:id'          =>  'groupes#edit'
  	post 'groupes/edit/:id'         =>  'groupes#update'
  	delete 'groupes/edit/:id'       =>  'groupes#destroy'


    get 'maraudes'                  =>  'maraudes#index'
    get 'maraudes/show/:id'         =>  'maraudes#show'
  	get 'maraudes/new'              =>  'maraudes#new'
  	post 'maraudes/new'             =>  'maraudes#create'
  	get 'maraudes/edit/:id'         =>  'maraudes#edit'
  	post 'maraudes/edit/:id'        =>  'maraudes#update'
  	delete 'maraudes/edit/:id'      =>  'maraudes#destroy'

    get 'structures'                =>  'structures#index'
    get 'structures/show/:id'       =>  'structures#show'
    get 'structures/new'            =>  'structures#new'
    post 'structures/new'           =>  'structures#create'
    get 'structures/edit/:id'       =>  'structures#edit'
    post 'structures/edit/:id'      =>  'structures#update'
    delete 'structures/edit/:id'    =>  'structures#destroy'


  	get 'rencontres/new/:id'        =>  'rencontres#new'
    post 'rencontres/new/:id'       =>  'rencontres#create'
	  get 'rencontres/edit_form/:id'  =>  'rencontres#edit_form'
    post 'rencontres/edit_form/:id' =>  'rencontres#post_form'
    get 'rencontres/edit/:id'       =>  'rencontres#edit'
    post 'rencontres/edit/:id'      =>  'rencontres#update'
    get 'rencontres/groupe/:id'     =>  'rencontres#new_groupe'
    post 'rencontres/groupe/:id'    =>  'rencontres#post_groupe'

    get 'stats'                     =>  'stats#show'
    post 'stats'                    =>  'stats#create'
    get 'stats/:ville/:categorie'   => 'stats#index'



end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right navbot">
        <% unless @current_user.nil? %>
          <li id="left-li"><%= link_to "#{@current_user.identifiant}", "/users/show/#{@current_user.id}" %></li>
          <li><%= link_to "Editer profil", "/users/edit/#{@current_user.id}" %></li>
          <li><%= link_to "Utilisateurs", users_path %></li>
          <li><%= link_to "Guide d'utilisation", guide_path %></li>
          <li><%= link_to "Listes", listes_path %></li>
          <li><%= link_to "Déconnexion", logout_path, method: "delete" %></li>

        <% end %>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right navtop">
        <li><%= link_to "Accueil",   root_path %></li>
        <% unless @current_user.nil? %>
          <li><%= link_to "Ajouter usager", '/usagers/new', "data-no-turbolink" => true %></li>
          <li><%= link_to "PQI", "/pqi" %></li>
          <li><%= link_to "Maraudes", "/maraudes" %></li>
          <li><%= link_to "Structures", "/structures" %></li>
          <li><%= link_to "Statistiques", "/stats" unless @current_user.benev? %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Samu Social 93</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">     
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>